name: Build MaiteInThePocket ~api~ and app

on:
  push:
    branches: ["master"]

jobs:
  # TODO add server build job
  build_app:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/app
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use node 18.6
        uses: actions/setup-node@v3
        with:
          node-version: "18.6"
      - name: Install dependencies
        run: npm ci
      - name: Build app
        run: npm run build